<?php

/**
 * @file
 * Contains kevla.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kevla_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kevla module.
    case 'help.page.kevla':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
